# Generated by Django 5.2.17 on 2026-09-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
